extends: "eslint:recommended"
root: true

env:
    es6: true

rules:
    no-unused-vars:
        - 0

globals:
    imports: false
    log: false
    InternalError: false
    uneval: false
    Iterator: false
    StopIteration: false
    Debugger: false
    window: false
    log: false
    logError: false
    print: false
    printerr: false
    GjsFileImporter: false
    imports: false
    ARGV: false
    ## Not in globals.js
    pkg: false
    _: false
    
