root: true

env:
    es6: true

rules:
    comma-dangle:
        - 2
        - "never"
    no-cond-assign:
        - 2
        - "always"
    no-console:
        - 2
    no-constant-condition:
        - 2
    no-debugger:
        - 2
    no-dupe-args:
        - 2
    no-dupe-keys:
        - 2
